---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="hybridadmin"
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox

notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
