---
# handlers file for unbound
- name: configure
  command: ./configure --enable-systemd --with-libevent
  args:
    chdir: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}"
    creates: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}/Makefile"

- name: make
  make:
    chdir: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}"

- name: make install
  make:
    chdir: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}"
    target: install

- name: install service
  copy:
    src: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}/contrib/unbound.service.in"
    dest: /etc/systemd/system/unbound.service
    mode: "0644"
    remote_src: yes
  notify:
    - systemctl daemon-reload

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart unbound
  systemd:
    name: unbound
    state: restarted
    daemon_reload: yes
