---

- name: converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    unbound_version: 1.14.0
    unbound_interface: 127.0.0.1
  tasks:
    - name: "Include unbound role"
      include_role:
        name: "hybridadmin.unbound"
