---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    unbound_version: 1.13.2
    unbound_interface: 127.0.0.1
  tasks:
    - name: "Include podman role"
      include_role:
        name: "hybridadmin.unbound"
