---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '21 21 21 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
#        uses: robertdebock/molecule-action@2.3.4
        uses: gofrolist/molecule-action@v2.0.1
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "centos"
            tag: "7"
          - image: "geerlingguy/docker-ubuntu2004-ansible"
            tag: "latest"
          - image: "fedora"
            tag: "31"
          - image: "fedora"
            tag: "latest"
          - image: "opensuse"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
#        uses: robertdebock/molecule-action@2.3.4
        uses: gofrolist/molecule-action@v2.0.1
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
