---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '21 21 21 * *'

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  molecule:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "geerlingguy/docker-centos8-ansible"
            tag: "latest"
          - image: "geerlingguy/docker-centos7-ansible"
            tag: "latest"
          - image: "geerlingguy/docker-ubuntu2004-ansible"
            tag: "latest"
          - image: "geerlingguy/docker-ubuntu1804-ansible"
            tag: "latest"
          - image: "geerlingguy/docker-fedora33-ansible"
            tag: "latest"
          - image: "geerlingguy/docker-fedora32-ansible"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: run molecule test
        uses: gofrolist/molecule-action@v2.0.1
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
